---
- name: Question 3 Creating group
  group:
    name: cloudadmins
    gid: 3000
    state: present
- name: Question 3 Creating users
  user:
    name: "{{ item.name }}"
    uid: "{{ item.id }}"
    state: present
    groups: cloudadmins,wheel
    generate_ssh_key: yes
  loop: "{{ user }}"
- name: Question 3 set authorized key taken from file
  authorized_key:
    user: "{{ item.name }}"
    state: present
    key: "{{ lookup('file', '/home/raopulkit599/.ssh/id_rsa.pub') }}"
  loop: "{{ user }}"